# -*- coding: utf-8 -*-

from . import models
from . import isp_crm_service_req_stage_model
from . import isp_crm_service_request_model
from . import isp_crm_solution
from . import isp_crm_problem
from . import isp_crm_team
from . import isp_crm_opportunity_model
from . import isp_crm_customer_model
from . import isp_crm_product_line_model
from . import isp_crm_cron_job_model
from . import isp_crm_solution_line_model
from . import isp_crm_sales_order_line_model
from . import isp_crm_check_login
from . import isp_crm_login
from . import isp_crm_connection_media
from . import isp_crm_connection_type
from . import isp_crm_service_type
from . import isp_crm_hd_solution
from . import isp_crm_hd_stage
from . import isp_crm_hd_tasks
from . import isp_crm_hd_ticket_complexity
from . import isp_crm_hd_ticket_history
from . import isp_crm_hd_type
from . import isp_crm_hd
from . import isp_crm_selfcare_service
from . import isp_crm_customer_package_history
from . import isp_crm_package_change
from . import isp_crm_hd_problem
from . import isp_crm_hd_td
from . import isp_crm_hd_solution
from . import isp_crm_hd_td_problem
from . import isp_crm_hd_td_stage
from . import isp_crm_hd_td_tasks
from . import isp_crm_hd_td_ticket_complexity
from . import isp_crm_hd_td_ticket_history
from . import isp_crm_hd_td_type
from . import isp_crm_hd_td_solution
from . import isp_crm_mail
from . import isp_crm_customer_invoice_status_model
from . import isp_crm_invoice_model
from . import isp_crm_package_history_model
from . import isp_crm_notify_user